### ISSUE TITLE
Bramus dependency

### ISSUE THREAD

**Issue by ghost** [jbleuzen/Picturo#9] opened 2013-09-25 14:21 UTC
Hello I'm trying to deploy picturo on my self hosted server and I'm getting this error about bramus

 PHP Fatal error:  Class 'Bramus\Router\Router' not found in /var/www/picturo/Picturo-master/index.php on line 13

**Comment by jbleuzen** [comment] 2013-09-26 07:35
Did you install Picturo at the root of your vhost or is it installed in a sub folder ?

Someone else reported problems with composer dependencies ([in Issue #8](https://github.com/jbleuzen/Picturo/issues/8#issuecomment-24991419)).
I'll have to take a closer look at how composer work before I can help you.

**Comment by ghost** [comment] 2013-09-26 07:42
it is installed in a subfolder

**Comment by jbleuzen** [comment] 2013-09-26 07:48
Ok, then it's probably because of this, that dependencies are not found...
I'll look into this.

**Comment by adngdb** [comment] 2013-11-08 10:39
I had this problem too, the reason being that the Bramus folder was empty. Here is what I had to do:
- remove the `vendor/bramus/` folder
- install composer
- run `composer.phar install`

I think we should remove that `bramus` folder from the repo, because running `composer.phar install` won't be updating it if the folder exists but is empty (which is the case when you download a zip of Picturo).

**Comment by jbleuzen** [comment] 2013-11-08 13:13
Ok, I was not aware that `vendor/bramus` was empty when downloading the zip...

I want to keep it simple at the moment and I don't think that instruct user to use composer is the right way.

I will fix the problem with the empty bramus folder in the week end.

**Comment by jbleuzen** [comment] 2013-11-08 22:25
Ok, it should be resolved now.
You can use Picturo without using `composer install`.

**Comment by jerrywham** [comment] 2013-11-11 01:53
This is not fixed. On mutualized, same error line 13.

**Comment by jbleuzen** [comment] 2013-11-13 13:22
I need to make some tests. But I really don't see why it doesn't work...

**Comment by jbleuzen** [comment] 2013-11-23 20:56
@jerrywham : I'm sorry but I can't reproduce this bug. Tested on my machine and my servers (none mutualized).

@AdrianGaudebert : Did you had a chance to test ?

**Comment by adngdb** [comment] 2013-12-13 17:39
Verified fixed. I downloaded the .zip, extracted it to my localhost, created the `content` folder (maybe that step should be explicitly explained in the documentation? ) and could access the website as intended.

**Comment by jbleuzen** [comment] 2013-12-13 20:40
Ok, thank Adrian !

@prysme01 : Could you retry please before I can close this issue ?

**Comment by jerrywham** [comment] 2013-12-15 22:47
I confirm : bug fixed.

**Comment by jbleuzen** [comment] 2013-12-16 09:52
Excellent.

Closing now !

**Closed as completed by jbleuzen** 2013-12-16 09:52 UTC
